#!/bin/bash
user_upgrade=UPGRADE
#user_update=UPDATE

read -p "Do you want to perform system update or upgrade:  " user_input

uppercase="${user_input^^}"
echo "System will $uppercase Shortly.."
sleep 3

if [[ $uppercase == $user_upgrade ]]; then 
	sleep 2 
	echo "Running System Upgrade"
	sudo apt upgrade
	echo "System Upgrade Completed Successfully"
else
	sleep 2
	echo "Running System Update"
	sudo apt update
	echo "System Update Completed Successfully"
fi
